"""Generate images for an article — through Doorman, or a local image CLI.

When Doorman is running with an image model configured, both steps below happen
there: one `POST /api/ask` writes the prompt and one `POST /api/image` renders
it. The user configured that model once, in the app that owns model access, and
should not need a second set of CLIs here. Everything else in this file is what
happens when Doorman is absent, older, or has no image model — which stays the
common case and is not a misconfiguration.

Note the Doorman path cannot pass the wiki's style *reference images*: its image
endpoint takes a prompt, a model and a size. The style *prompt* still applies.

The local path is two steps, mirroring how the user works by hand:

1. **Claude writes the prompt.** The `claude` CLI turns the article context + a
   short human description into one vivid image-generation prompt.
2. **agy/gemini renders it.** The image CLI runs headless (`--print`), told to
   use its built-in image tool and save a PNG into the article's own folder.
   That folder is passed with `--add-dir` so the CLI can see earlier images and
   keep the style consistent across one article.

The PNG is then ingested into the wiki (so it displays and exports like any
uploaded image) while the original file stays in the article folder for the next
generation's `--add-dir` context.
"""
from __future__ import annotations

import re
import subprocess
from pathlib import Path

from . import clirun, config, db, render, shellenv, store


_REF_EXTS = {".png", ".jpg", ".jpeg", ".webp", ".gif"}


def article_image_dir(wiki: str, slug: str) -> Path:
    """Per-article image folder — one place per article, for --add-dir consistency."""
    d = config.DATA_DIR / "images" / wiki / slug
    d.mkdir(parents=True, exist_ok=True)
    return d


def style_reference_dir(wiki: str) -> Path:
    """Per-wiki folder of reference images that define the wiki's art style. Its
    contents are handed to the image CLI via --add-dir so it can match them."""
    d = config.DATA_DIR / "style_refs" / wiki
    d.mkdir(parents=True, exist_ok=True)
    return d


def _safe_name(name: str) -> str:
    import os
    return os.path.basename(name or "").replace("/", "_").strip() or "image"


def list_style_refs(wiki: str) -> list[str]:
    d = style_reference_dir(wiki)
    return sorted(p.name for p in d.glob("*") if p.suffix.lower() in _REF_EXTS)


def save_style_ref(wiki: str, filename: str, data: bytes) -> str:
    name = _safe_name(filename)
    (style_reference_dir(wiki) / name).write_bytes(data)
    return name


def delete_style_ref(wiki: str, filename: str) -> bool:
    d = style_reference_dir(wiki)
    p = d / _safe_name(filename)
    if p.exists() and p.parent == d:
        p.unlink()
        return True
    return False


def _next_filename(folder: Path, description: str) -> str:
    base = render.slugify(description)[:40] or "image"
    n = len(list(folder.glob("*.png"))) + 1
    return f"{base}-{n}.png"


def write_image_prompt(title: str, article_md: str, description: str,
                       style: str = "", model: str = "", slug: str = "") -> str:
    """Ask a model to craft a vivid image prompt — a Doorman agent when there is
    one, else the local claude CLI. Falls back to the raw description if neither
    is available or either errors: a plain description still renders."""
    from . import doorman

    excerpt = (article_md or "")[:1500]
    style_line = (f"Overall visual style for this wiki (apply it faithfully): "
                  f"{style}\n\n" if style.strip() else "")
    ask = (
        "You write a single vivid prompt for an AI image generator. Output ONLY "
        "the prompt text — no preamble, no quotes, no markdown.\n\n"
        f"{style_line}"
        f"Wiki article: {title}\n\n{excerpt}\n\n"
        f"The user wants an illustration described as: {description}\n\n"
        "Write one detailed image-generation prompt (subject, composition, style, "
        "palette, mood) that suits this article. Under 100 words."
    )
    got = doorman.ask(ask, wiki=db.active_wiki(), page=slug, timeout=120)
    if got is not None:
        return ((got.get("answer") or "").strip() if got.get("ok") else "") or description

    claude = shellenv.which("claude")
    if not claude:
        return description
    argv = [claude, "-p", ask] + (["--model", model] if model else [])
    try:
        proc = clirun.run("claude:image-prompt", argv, 120)
    except Exception:
        return description
    out = re.sub(r"\x1b\[[0-9;]*m", "", (proc.stdout or "").strip())
    return out or description


def _ingest(folder: Path, name: str, data: bytes, description: str,
            img_prompt: str, label: str) -> dict:
    """Save generated bytes into the article folder, then into the wiki.

    The file stays in the per-article folder on purpose: that folder is what the
    local CLI is later shown with --add-dir to keep an article's images
    consistent, and an image made through Doorman should count towards that too.
    """
    path = folder / name
    path.write_bytes(data)
    image_id = store.save_image(path.name, "image/png", data)
    url = f"/image/{image_id}/{path.name}"
    return {"ok": True, "url": url, "markdown": f"![{description}]({url})",
            "prompt": img_prompt, "path": str(path), "label": label}


def generate(slug: str, description: str, image_cli: str = "agy",
             model: str = "", timeout: int = 300) -> dict:
    """Generate an image for page `slug` from a short description. Synchronous
    (Doorman over HTTP, or a local CLI) — call in a worker thread from async
    code. The result carries a `label` naming whichever one rendered it."""
    from . import doorman

    description = (description or "").strip()
    if not description:
        return {"ok": False, "error": "Describe the image first."}
    page = store.get_page(slug)
    if not page:
        return {"ok": False, "error": f"No page '{slug}'."}

    wiki = db.active_wiki()
    folder = article_image_dir(wiki, slug)
    style = db.get_setting("image_style_prompt", "")
    img_prompt = write_image_prompt(page["title"], page["markdown"], description,
                                    style, slug=slug)

    # Doorman renders it when it has an image model. None means it can't — take
    # the CLI path without a word. A dict that isn't ok means it tried and
    # failed, which Doorman signals deliberately and the user should see.
    style_line = f"Overall visual style: {style}\n\n" if style.strip() else ""
    got = doorman.image(f"{img_prompt}\n\n{style_line}".strip(),
                        size="1024x1024", timeout=timeout)
    if got is not None:
        if not got.get("ok"):
            return {"ok": False, "error": got.get("error", "Doorman couldn't render.")}
        return _ingest(folder, _next_filename(folder, description), got["data"],
                       description, img_prompt, got.get("label", "Doorman"))

    cli = shellenv.which(image_cli)
    if not cli:
        return {"ok": False,
                "error": f"`{image_cli}` CLI not found. Install it, or set a "
                         f"different image CLI in Settings → Images."}

    ref_dir = style_reference_dir(wiki)
    refs = list_style_refs(wiki)

    save_path = folder / _next_filename(folder, description)
    ref_line = (
        f"Reference images that define the required art style are in {ref_dir} "
        f"({len(refs)} image{'s' if len(refs) != 1 else ''}) — study them and match "
        f"their style, palette, and linework closely.\n\n" if refs else ""
    )
    instruction = (
        f"{img_prompt}\n\n{style_line}{ref_line}"
        f"Render at 1024x1024 px. Use your built-in image generation tool and save "
        f"the result as a PNG to {save_path}. If {folder} already contains images, "
        f"keep the visual style consistent with them."
    )
    argv = [cli]
    if model:
        argv += ["-m", model]
    argv += ["--add-dir", str(folder)]
    if refs:                                # let the CLI see the style references
        argv += ["--add-dir", str(ref_dir)]
    argv += ["--dangerously-skip-permissions", "--print", instruction]

    before = set(folder.glob("*.png"))
    try:
        proc = clirun.run(f"{image_cli}:image", argv, timeout)
    except subprocess.TimeoutExpired:
        return {"ok": False, "error": f"Image generation timed out after {timeout}s."}
    except Exception as exc:
        return {"ok": False, "error": f"Failed to run {image_cli}: {exc}"}

    # Prefer the exact path; otherwise take the newest PNG that appeared.
    img_file = save_path if save_path.exists() else None
    if img_file is None:
        fresh = sorted(set(folder.glob("*.png")) - before,
                       key=lambda p: p.stat().st_mtime)
        img_file = fresh[-1] if fresh else None
    if img_file is None:
        out = ((proc.stdout or "") + "\n" + (proc.stderr or "")).strip()
        return {"ok": False,
                "error": f"{image_cli} didn't produce a PNG. Output: {out[:400]}"}

    data = img_file.read_bytes()
    image_id = store.save_image(img_file.name, "image/png", data)
    url = f"/image/{image_id}/{img_file.name}"
    return {"ok": True, "url": url, "markdown": f"![{description}]({url})",
            "prompt": img_prompt, "path": str(img_file),
            "label": f"{image_cli} CLI" + (f" · {model}" if model else "")}
